name: Rollback Prod

on:
  workflow_dispatch:
    inputs:
      TAG_NAME:
        required: true
        description: Type tag name to confirm.
        type: string
      CONFIRMATION:
        required: true
        description: Type 'DEPLOY TO PRODUCTION' to confirm.
        type: string

jobs:
  confirm:
    name: Confirm
    runs-on: ubuntu-latest
    steps:
      - run: |
          [ "refs/tags/${{ inputs.TAG_NAME }}" = "${{ github.ref }}" ]
      - run: |
          [ "${{ inputs.CONFIRMATION }}" = "DEPLOY TO PRODUCTION" ]

  execute:
    name: Execute
    runs-on: ubuntu-latest
    needs:
      - confirm
    steps:
      - run: echo "executed."
